### ISSUE TITLE
error in setup.py

### ISSUE THREAD

**Issue by greenteaturtle** [jalexw/bibliu_sucks#3]
hope I am wrong here, but there's problem with setup.py at line 27
the n_pages has to be str(n_pages) in order to run it without bug
just a complete newbie here so correct me if I am wrong

**Comment by jalexw** [comment]
You're absolutely correct -- thanks for pointing that out! I just pushed the fix.

I'm too used to JavaScript just letting me print anything without making it a string first... My bad :(
