### ISSUE TITLE
suggest ripper with a longer tipper timer 

### ISSUE THREAD

**Issue by Mikhael913** [jalexw/bibliu_sucks#6]
There have been several instances where the automation rips a page that has yet to be loaded, as the reader needs to load in the next batch of sections, even though a local copy exists in the system. The issue doesn't occur if the user is manually ripping by sections as loaded in the reader, but the issue occurs when the user is ripping from the first to the last page where pages would exceed a few hundred pages.

![image](https://user-images.githubusercontent.com/108319694/176098329-35afe2dd-ceef-4afe-9623-23cbdeb0276f.png)

**Comment by jalexw** [comment]
Hmmm, I didn't run into this issue as my internet is quite fast so the pages loaded near instantly for me.

As a work around you could change the delay on `line 100 of ripper.py` to give pages more time to load:
```python
# Wait a little bit to allow the page to fully load
sleep(modify_delay_randomly(0.5))
```
into:
```python
# Wait a little bit to allow the page to fully load
sleep(modify_delay_randomly(2.0))
```
This will take longer to get through all of the pages although it should solve your page loading problem.

**Comment by jalexw** [comment]
I've pushed a new GUI version that has a slider that allows changing the delay between typing a new page number and actually taking the screenshot. Should help out people who have slow internet.

<img width="478" alt="gui_screenshot" src="https://user-images.githubusercontent.com/51729845/195499300-aa7141e3-7294-493f-8bb3-eac9be91623c.png">

**Comment by Mikhael913** [comment]
Thank you very much for your most recent update, I have been busy with training for my license for these past few months. I have started to introduce this with other coursemates who are in similar circumstances, yet lacking experience in programming. Cheers.
